[tasks.default]
alias = "lcov"

# Format
[tasks.format]
command = "cargo"
args = ["fmt"]

# Check build
[tasks.check]
install_crate = "cargo-all-features"
command = "cargo"
args = ["check-all-features"]
dependencies = ["format"]

# Clippy
[tasks.clippy]
command = "cargo"
args = ["clippy","--tests"]
dependencies = ["check"]

# Check for dead dependencies
[tasks.udeps]
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps"]
dependencies = ["clippy"]

# Audit dependencies
[tasks.audit]
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]
dependencies = ["udeps"]

# Test
[tasks.test]
command = "cargo"
args = ["test-all-features"]
dependencies = ["audit"]

# Coverage
[tasks.lcov]
install_crate = "cargo-llvm-cov"
command = "cargo"
args = ["llvm-cov", "--lcov", "--output-path", "lcov.info"]
dependencies = ["test"]