on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install gitlint
        run: sudo apt install gitlint
        
      - name: Run gitlint
        run: gitlint

      - name: Use nightly
        run: rustup default nightly

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Run cargo-make
        run: cargo make

      - name: Codecov
        uses: codecov/codecov-action@v3